[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/themes/spaceship-prompt"]
    type = "archive"
    #url = "https://github.com/spaceship-prompt/spaceship-prompt/archive/master.tar.gz"
    url = "https://github.com/spaceship-prompt/spaceship-prompt/archive/refs/tags/v4.15.0.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
 [".tmux-themepack"]
    type = "archive"
    url = "https://github.com/jimeh/tmux-themepack/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".config/nvim"]
    type = "git-repo"
    url = "https://github.com/swierq/neovim-config"
    refreshPeriod = "168h"
