[".local/share/zap"]
    type = "archive"
    url = "https://github.com/zap-zsh/zap/archive/refs/tags/1.2.0.zip"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".config/nvim"]
    type = "git-repo"
    url = "https://github.com/swierq/neovim-config"
    refreshPeriod = "168h"
[".tmuxifier"]
    type = "git-repo"
    url = "https://github.com/jimeh/tmuxifier.git"
    refreshPeriod = "168h"

[".fzf"]
    type = "git-repo"
    url = "https://github.com/junegunn/fzf.git"
    refreshPeriod = "168h"
